<?php

use App\Http\Controllers\Api\Auth\LoginController as LoginCon;
use App\Http\Controllers\Api\LocationController as LocationCon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
 */

// Login route
Route::post('/login', [LoginCon::class, 'login'])->name('api.login');

// Logout route protected by auth middleware
Route::post('/logout', [LoginCon::class, 'logout'])->name('api.logout')->middleware('auth:api');

// One user will be generated by User seeder so not needed
// Route::post('/register', [RegisterCon::class, 'register])->name('api.register');

// Unauthenticated routes
Route::prefix('/get')->group(function () {
    //
});

Route::prefix('/post')->group(function () {
    //
});

// Authenticated routes
Route::middleware(['auth:api'])->prefix('auth')->name('auth')->group(function () {

    Route::prefix('get')->group(function () {
        //
    });

    Route::prefix('post')->group(function () {
        //
    });

});
